/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2023-04-03 07:24:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612850415545L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMVC03/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMVC03/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Spring MVC03</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  \t$(document).ready(function() {\r\n");
      out.write("  \t\tloadList();\r\n");
      out.write("  \t});\r\n");
      out.write("  \tfunction loadList() {\r\n");
      out.write("\t\t// 서버와 통신 : 게시판 리스트 가져오기\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"board/all\",\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : makeView,\r\n");
      out.write("\t\t\terror : function () {\r\n");
      out.write("\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("  \tfunction makeView(data) {\t// data = [{\t}, {\t}, {\t},,,]\r\n");
      out.write("\t\tvar listHtml = \"<table class='table table-bordered'>\";\r\n");
      out.write("\t\tlistHtml += \"<tr>\";\r\n");
      out.write("\t\tlistHtml += \"<td>번호</td>\";\r\n");
      out.write("\t\tlistHtml += \"<td>제목</td>\";\r\n");
      out.write("\t\tlistHtml += \"<td>작성자</td>\";\r\n");
      out.write("\t\tlistHtml += \"<td>작성일</td>\";\r\n");
      out.write("\t\tlistHtml += \"<td>조회수</td>\";\r\n");
      out.write("\t\tlistHtml += \"</tr>\";\r\n");
      out.write("\t\t$.each(data, function (index, obj) {\r\n");
      out.write("\t\t\tlistHtml += \"<tr>\";\r\n");
      out.write("\t\t\tlistHtml += \"<td>\"+obj.idx+\"</td>\";\r\n");
      out.write("\t\t\tlistHtml += \"<td id='t\"+obj.idx+\"'><a href='javascript:goContent(\"+obj.idx+\")'>\"+obj.title+\"</a></td>\";\r\n");
      out.write("\t\t\tlistHtml += \"<td>\"+obj.writer+\"</td>\";\r\n");
      out.write("\t\t\tlistHtml += \"<td>\"+obj.indate.split(' ')[0]+\"</td>\";\r\n");
      out.write("\t\t\tlistHtml += \"<td id='cnt\"+obj.idx+\"'>\"+obj.count+\"</td>\";\r\n");
      out.write("\t\t\tlistHtml += \"</tr>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlistHtml += \"<tr id='c\"+obj.idx+\"' style='display:none'>\";\r\n");
      out.write("\t\t\tlistHtml += \"<td>내용</td>\";\r\n");
      out.write("\t\t\tlistHtml += \"<td colspan='4'>\";\r\n");
      out.write("\t\t\tlistHtml += \"<textarea id='ta\"+obj.idx+\"' readonly rows='7' class='form-control'></textarea>\"\r\n");
      out.write("\t\t\tlistHtml += \"<br/>\";\r\n");
      out.write("\t\t\tlistHtml += \"<span id='ub\"+obj.idx+\"'><button class='btn btn-success btn-sm' onclick='goUpdateForm(\"+obj.idx+\")'>수정화면</button></span>&nbsp;\";\r\n");
      out.write("\t\t\tlistHtml += \"<button class='btn btn-warning btn-sm' onclick='goDelete(\"+obj.idx+\")'>삭제</button>\";\r\n");
      out.write("\t\t\tlistHtml += \"</td>\";\r\n");
      out.write("\t\t\tlistHtml += \"</tr>\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlistHtml += \"<tr>\";\r\n");
      out.write("\t\tlistHtml += \"<td colspan='5'>\";\r\n");
      out.write("\t\tlistHtml += \"<button class='btn btn-primary btn-sm' onclick='goForm()'>글쓰기</button>\";\r\n");
      out.write("\t\tlistHtml += \"</td>\";\t\r\n");
      out.write("\t\tlistHtml += \"</tr>\";\r\n");
      out.write("\t\tlistHtml += \"</table>\";\r\n");
      out.write("\t\t// id가 view인곳에 table이 들어감\r\n");
      out.write("\t\t$(\"#view\").html(listHtml);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#view\").css(\"display\", \"block\");\r\n");
      out.write("\t\t$(\"#wfrom\").css(\"display\", \"none\");\r\n");
      out.write("\t}\r\n");
      out.write("  \t\r\n");
      out.write("  \tfunction goForm() {\r\n");
      out.write("\t\t$(\"#view\").css(\"display\", \"none\");\t// 감추고\r\n");
      out.write("\t\t$(\"#wfrom\").css(\"display\", \"block\");\t// 보이고\r\n");
      out.write("\t}\r\n");
      out.write("  \t\r\n");
      out.write("  \tfunction goList() {\r\n");
      out.write("\t\t$(\"#view\").css(\"display\", \"block\");\r\n");
      out.write("\t\t$(\"#wfrom\").css(\"display\", \"none\");\r\n");
      out.write("\t}\r\n");
      out.write("  \t\r\n");
      out.write("  \tfunction goInsert() {\r\n");
      out.write("\t\t// var title = $(\"#title\").val();\r\n");
      out.write("\t\t// var content = $(\"content\").val();\r\n");
      out.write("\t\t// var writer = $(\"writer\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar fData = $(\"#frm\").serialize();\t// 폼 안에 있는 모든 데이터를 한줄로 가져옴\r\n");
      out.write("\t\t// alert(fData);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"board/new\" ,\r\n");
      out.write("\t\t\ttype: \"post\" ,\r\n");
      out.write("\t\t\tdata: fData ,\r\n");
      out.write("\t\t\tsuccess: loadList ,\r\n");
      out.write("\t\t\terror: function () {\r\n");
      out.write("\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 폼 초기화\r\n");
      out.write("\t\t// $(\"#title\").val(\"\");\r\n");
      out.write("\t\t// $(\"#content\").val(\"\");\r\n");
      out.write("\t\t// $(\"#writer\").val(\"\");\r\n");
      out.write("\t\t$(\"#fclear\").trigger(\"click\");\t// trigger 프로그램에서 클릭하게 설정\r\n");
      out.write("\t}\r\n");
      out.write("  \t\r\n");
      out.write("  \tfunction goContent(idx) {\t// idx, 10, 9, 8...\r\n");
      out.write("  \t\tif($(\"#c\"+idx).css(\"display\")==\"none\"){\t\t// 닫혀있을경우\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\t$.ajax({\r\n");
      out.write("  \t\t\t\turl: \"board/\"+idx,\r\n");
      out.write("  \t\t\t\ttype: \"get\",\r\n");
      out.write("  \t\t\t\tdataType: \"json\",\r\n");
      out.write("  \t\t\t\tsuccess: function (data) {\t// data={\"content\": ~~~}\r\n");
      out.write("\t\t\t\t\t$(\"#ta\"+idx).val(data.content);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function () {\r\n");
      out.write("\t\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("  \t\t\t});\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\t$(\"#c\"+idx).css(\"display\", \"table-row\");\t// 보이게 block이 아닌 table-row로 해야 스타일이 먹힌다.\r\n");
      out.write("  \t\t\t$(\"#ta\"+idx).attr(\"readonly\", true);\r\n");
      out.write("  \t\t} else {\r\n");
      out.write("  \t\t\t$(\"#c\"+idx).css(\"display\", \"none\");\t// 감추게함\r\n");
      out.write("  \t\t\t$.ajax({\r\n");
      out.write("  \t\t\t\turl: \"board/count/\"+idx,\r\n");
      out.write("  \t\t\t\ttype: \"put\",\r\n");
      out.write("  \t\t\t\tdataType: \"json\",\r\n");
      out.write("  \t\t\t\tsuccess: function (data) {\r\n");
      out.write("\t\t\t\t\t$(\"#cnt\"+idx).text(data.count);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function () {\r\n");
      out.write("\t\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("  \t\t\t});\r\n");
      out.write("  \t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("  \t\r\n");
      out.write("  \tfunction goDelete(idx) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"board/\"+idx,\r\n");
      out.write("\t\t\ttype: \"delete\",\r\n");
      out.write("\t\t\tsuccess: loadList,\r\n");
      out.write("\t\t\terror: function () {\r\n");
      out.write("\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("  \t\r\n");
      out.write("  \tfunction goUpdateForm(idx) {\t// idx = 10, 7, ...\r\n");
      out.write("\t\t$(\"#ta\"+idx).attr(\"readonly\", false);\t\t// attr = attribute readonly를 취소해라 readonly는 style이 아님\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar title = $(\"#t\"+idx).text();\t\t// 수정할 제목의 원래 제목을 가져옴\r\n");
      out.write("\t\tvar newInput = \"<input type='text' id='nt\"+idx+\"' class='form-control' value='\"+title+\"'/>\";\r\n");
      out.write("\t\t$(\"#t\"+idx).html(newInput);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar newButton = \"<button class='btn btn-info btn-sm' onclick='goUpdate(\"+idx+\")'>수정</button>\";\t\t// 수정화면버튼을 수정버튼으로 변경\r\n");
      out.write("\t\t$(\"#ub\"+idx).html(newButton);\t\r\n");
      out.write("  \t}\r\n");
      out.write("  \t\r\n");
      out.write("  \t// 글 수정을 할려면 data를 json 형태로 만들고 주고받아야함. JSON.stringify\r\n");
      out.write("  \t// contentType: 'application/json; charset=utf-8'\r\n");
      out.write("  \tfunction goUpdate(idx) {\r\n");
      out.write("\t\tvar title=$(\"#nt\"+idx).val();\r\n");
      out.write("\t\tvar content=$(\"#ta\"+idx).val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"board/update\",\r\n");
      out.write("\t\t\ttype: \"put\",\r\n");
      out.write("\t\t\tcontentType:'application/json;charset=utf-8',\r\n");
      out.write("\t\t\tdata: JSON.stringify({\"idx\":idx, \"title\":title, \"content\":content}),\r\n");
      out.write("\t\t\tsuccess: loadList,\r\n");
      out.write("\t\t\terror: function () {\r\n");
      out.write("\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<div class=\"container\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("  <h2>Spring MVC03</h2>\r\n");
      out.write("  <div class=\"panel panel-default\">\r\n");
      out.write("    <div class=\"panel-heading\">Board</div>\r\n");
      out.write("    <div class=\"panel-body\" id=\"view\">Panel Content</div>\r\n");
      out.write("    <div class=\"pannel-body\" id=\"wfrom\" style=\"display: none\">\r\n");
      out.write("    \t<form id=\"frm\">\r\n");
      out.write("\t    \t<table class=\"table\">\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>제목</td>\r\n");
      out.write("\t    \t\t\t<td><input type=\"text\" id=\"title\" name=\"title\" class=\"form-control\"/> </td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t    \t\t\t<td>내용</td>\r\n");
      out.write("\t    \t\t\t<td><textarea rows=\"7\" class=\"form-control\" id=\"content\" name=\"content\"></textarea> </td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>작성자</td>\r\n");
      out.write("\t    \t\t\t<td><input type=\"text\" id=\"writer\" name=\"writer\" class=\"form-control\"/></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t    \t\t\t\t<button type=\"button\" class=\"btn btn-success btn-sm\" onclick=\"goInsert()\">등록</button>\r\n");
      out.write("\t    \t\t\t\t<button type=\"reset\" class=\"btn btn-warning btn-sm\" id=\"fclear\">취소</button>\r\n");
      out.write("\t    \t\t\t\t<button type=\"button\" class=\"btn btn-info btn-sm\" onclick=\"goList()\">리스트</button>\r\n");
      out.write("\t    \t\t\t</td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t</table>\r\n");
      out.write("    \t</form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"panel-footer\">인프런_스프1탄_박매일</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
